name = "MPSKitParallel"
uuid = "9e7a2049-d464-45e7-afa7-8ebdb5f1c98e"
version = "0.1.0"
authors = ["Andreas Feuerpfeil <development@manybodylab.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPILargeCounts = "03b5a6d4-3f85-4eec-9d38-a1f1826bd98e"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorKitManifolds = "11fa318c-39cb-4a83-b1ed-cdc7ba1e3684"
VectorInterface = "409d34a3-91d5-4945-b6ec-7529ddf182d8"

[compat]
LinearAlgebra = "1.12.0"
MPI = "0.20.23"
MPILargeCounts = "0.1.0"
MPSKit = "0.13.8"
MacroTools = "0.5.16"
OhMyThreads = "0.8.3"
Pkg = "1.12.0"
TensorKit = "0.15.2, 0.16"
TensorKit = "0.15.2,0.16"
TensorKitManifolds = "0.7.3"
VectorInterface = "0.5.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
