[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MPSKitParallel = "9e7a2049-d464-45e7-afa7-8ebdb5f1c98e"

[compat]
Documenter = "1"
Literate = "2"
MPSKitParallel = "0.1"
